apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
        - name: locations
          image: dallasvaughn/locations
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: weather
            - name: MONGO_URI
              value: 'mongodb://locations-mongo-srv:27017/locations'
            # arguably not an issue to hardcode URL as a string here; need to be connected to cluster to access it; not associated with any particular user info
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: locations-srv
spec:
  selector:
    app: locations
  ports:
    - name: locations
      protocol: TCP
      port: 3000
      targetPort: 3000
